server {
    listen 8080;
    server_name _;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    root /usr/share/nginx/html;
    index index.html;

    # .py dosyalarını text olarak servis et
    types {
        text/plain py;
    }

    location = / {
        rewrite ^ /web-ui/ last;
    }

    location / {
        try_files $uri $uri/ =404;
    }

    location /web-ui/ {
        try_files $uri $uri/ /web-ui/index.html;
    }
}
