server {
    listen 8080;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location = / {
        return 302 /web-ui/;
    }

    location / {
        try_files $uri $uri/ =404;
    }

    location /web-ui/ {
        try_files $uri $uri/ /web-ui/index.html;
    }

    types {
        text/plain py;
    }
}
